"""1

Revision ID: 5a2ddd7fa1d3
Revises: a59548292113
Create Date: 2025-05-31 13:24:51.265991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a2ddd7fa1d3'
down_revision: Union[str, None] = 'a59548292113'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nfts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('nfts_user_id_fkey'), type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nfts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('nfts_user_id_fkey'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
