"""3

Revision ID: 7881314be479
Revises: 743ea6862abf
Create Date: 2025-05-30 21:32:15.949253

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7881314be479"
down_revision: Union[str, None] = "743ea6862abf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("egithub_username", sa.String(), nullable=True))
        batch_op.drop_constraint(batch_op.f("users_email_key"), type_="unique")
        batch_op.drop_constraint(batch_op.f("users_nickname_key"), type_="unique")
        batch_op.create_unique_constraint(
            batch_op.f("users_egithub_username_key"), ["egithub_username"]
        )
        batch_op.drop_column("nickname")
        batch_op.drop_column("telegram_id")
        batch_op.drop_column("email")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column("telegram_id", sa.VARCHAR(), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "nickname", sa.VARCHAR(length=50), autoincrement=False, nullable=False
            )
        )
        batch_op.drop_constraint(
            batch_op.f("users_egithub_username_key"), type_="unique"
        )
        batch_op.create_unique_constraint(
            batch_op.f("users_nickname_key"),
            ["nickname"],
            postgresql_nulls_not_distinct=False,
        )
        batch_op.create_unique_constraint(
            batch_op.f("users_email_key"),
            ["email"],
            postgresql_nulls_not_distinct=False,
        )
        batch_op.drop_column("egithub_username")

    # ### end Alembic commands ###
